

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("","",1,1,1);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("","",1,1,1);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("","",1,1,1);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("","",1,1,1);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("","",1,1,1);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("","",1,1,1);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("","",1,1,1);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("","",1,1,1);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("","",1,1,1);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("","",1,1,1);

INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);
INSERT INTO users (name, age) VALUES ("a",1);

INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10,1,2);
